import { z } from 'zod';

export const updateSiteConfigSchema = z.object({
  body: z.object({
    appName: z.string().min(1).max(100).optional(),
    appTagline: z.string().optional(),
    appLogoUrl: z.string().optional().or(z.literal('')),
    heroHeadline: z.string().optional(),
    heroSubtitle: z.string().optional(),
    announceText: z.string().optional(),
    announceLink: z.string().optional(),
    dmcaEmail: z.string().email().optional().or(z.literal('')),
    termsOfService: z.string().optional(),
    privacyPolicy: z.string().optional(),
    aboutUs: z.string().optional(),
    isMaintenanceMode: z.boolean().optional(),
    maintenanceMessage: z.string().optional(),
    allowNewRegistrations: z.boolean().optional(),
    allowCreatorApplications: z.boolean().optional(),
    enableGlobalChat: z.boolean().optional(),
    seoTitle: z.string().optional(),
    seoDescription: z.string().optional(),
    seoKeywords: z.string().optional(),
    ogImageUrl: z.string().optional().or(z.literal('')),
    gaTrackingId: z.string().optional(),
    adClient: z.string().optional(),
    playStoreUrl: z.string().optional().or(z.literal('')),
    appStoreUrl: z.string().optional().or(z.literal('')),
    pointToFiatRate: z.number().min(0).optional(),
    minWithdrawalPoints: z.number().min(0).optional(),
    creatorRevenueSharePercent: z.number().min(0).max(100).optional(),
    maxDailyAdPoints: z.number().min(0).optional(),
    referralBonusPercent: z.number().min(0).max(100).optional(),
    referralActiveMonths: z.number().min(0).optional(),
    customAdScript: z.string().optional(),
    discord: z.string().optional(),
    twitter: z.string().optional(),
    telegram: z.string().optional(),
    youtube: z.string().optional(),
    instagram: z.string().optional(),
    facebook: z.string().optional(),
    reddit: z.string().optional(),
  }),
});
